/* 
 * Chomp Food Database API Documentation
 *
 * ## Important An **[API key](https://chompthis.com/api/)** is required for access to this API. Get yours at **[https://chompthis.com/api](https://chompthis.com/api/)**.  ### Getting Started   * **[Subscribe](https://chompthis.com/api/#pricing)** to the API.   * Scroll down and click the \"**Authorize**\" button.   * Enter your API key into the \"**value**\" input, click the \"**Authorize**\" button, then click the \"**Close**\" button.   * Scroll down to the section titled \"**default**\" and click on the API endpoint you wish to use.   * Click the \"**Try it out**\" button.   * Enter the information the endpoint requires.   * Click the \"**Execute**\" button.  ### Example    * Branded food response object: **[View example &raquo;](https://raw.githubusercontent.com/chompfoods/examples/master/branded-food-response-object.json)**   * Ingredient response object: **[View example &raquo;](https://raw.githubusercontent.com/chompfoods/examples/master/ingredient-response-object.json)**  ### How Do I Find My API Key?   * Your API key was sent to the email address you used to create your subscription.   * You will also find your API key in the **[Client Center](https://chompthis.com/api/manage.php)**.   * Read **[this article](https://desk.zoho.com/portal/chompthis/kb/articles/how-do-i-find-my-api-key)** for more information.  ||| | - -- -- -- | - -- -- -- - | | [Knowledge Base](https://desk.zoho.com/portal/chompthis/kb/chomp) | [Pricing](https://chompthis.com/api/) | | [Attribution](https://chompthis.com/api/docs/attribution.php) | [Cost Calculator](https://chompthis.com/api/cost-calculator.php) | | [Terms & License](https://chompthis.com/api/terms.php) | [Database Search](https://chompthis.com/api/lookup.php) | | [Support](https://chompthis.com/api/ticket-new.php) | [Query Builder](https://chompthis.com/api/build.php) | | [Client Center](https://chompthis.com/api/manage.php) | | 
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// An object containing this item&#x27;s ingredients in order of highest value to least
    /// </summary>
    [DataContract]
        public partial class BrandedFoodObjectIngredients :  IEquatable<BrandedFoodObjectIngredients>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BrandedFoodObjectIngredients" /> class.
        /// </summary>
        /// <param name="chomp">Ingredients for this item from Chomp&#x27;s internal database.</param>
        /// <param name="usda">This branded food item&#x27;s ingredients, according to the USDA.</param>
        public BrandedFoodObjectIngredients(string chomp = default(string), string usda = default(string))
        {
            this.Chomp = chomp;
            this.Usda = usda;
        }
        
        /// <summary>
        /// Ingredients for this item from Chomp&#x27;s internal database
        /// </summary>
        /// <value>Ingredients for this item from Chomp&#x27;s internal database</value>
        [DataMember(Name="chomp", EmitDefaultValue=false)]
        public string Chomp { get; set; }

        /// <summary>
        /// This branded food item&#x27;s ingredients, according to the USDA
        /// </summary>
        /// <value>This branded food item&#x27;s ingredients, according to the USDA</value>
        [DataMember(Name="usda", EmitDefaultValue=false)]
        public string Usda { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BrandedFoodObjectIngredients {\n");
            sb.Append("  Chomp: ").Append(Chomp).Append("\n");
            sb.Append("  Usda: ").Append(Usda).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BrandedFoodObjectIngredients);
        }

        /// <summary>
        /// Returns true if BrandedFoodObjectIngredients instances are equal
        /// </summary>
        /// <param name="input">Instance of BrandedFoodObjectIngredients to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BrandedFoodObjectIngredients input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Chomp == input.Chomp ||
                    (this.Chomp != null &&
                    this.Chomp.Equals(input.Chomp))
                ) && 
                (
                    this.Usda == input.Usda ||
                    (this.Usda != null &&
                    this.Usda.Equals(input.Usda))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Chomp != null)
                    hashCode = hashCode * 59 + this.Chomp.GetHashCode();
                if (this.Usda != null)
                    hashCode = hashCode * 59 + this.Usda.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
