/* 
 * Chomp Food Database API Documentation
 *
 * __Important:__   - An __[API key](https://chompthis.com/api/)__ is required for access to this API.   - Get yours at __[https://chompthis.com/api](https://chompthis.com/api/)__.  - -- --  __Getting Started:__   - __[Subscribe](https://chompthis.com/api/#pricing)__ to the API.   - Scroll down and click the \"__Authorize__\" button.   - Enter your API key into the \"__value__\" input, click the \"__Authorize__\" button, then click the \"__Close__\" button.   - Scroll down to the section titled \"__default__\" and click on the API endpoint you wish to use.   - Click the \"__Try it out__\" button.   - Enter the information the endpoint requires.   - Click the \"__Execute__\" button.  __Example:__    - Branded Food: __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/branded-food-response-object.json)__ API response object.   - Ingredient: __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/ingredient-response-object.json)__ API response object.  - -- --  __How Do I Find My API Key?__   - Your API key was sent to the email address you used to create your subscription.   - You will also find your API key in the __[Client Center](https://chompthis.com/api/manage.php)__.   - _Read __[this article](https://desk.zoho.com/portal/chompthis/kb/articles/how-do-i-find-my-api-key)__ for more information._  ||| | - -- -- -- | - -- -- -- - | | [Knowledge Base](https://desk.zoho.com/portal/chompthis/kb/chomp) | [Pricing](https://chompthis.com/api/) | | [Attribution](https://chompthis.com/api/docs/attribution.php) | [Cost Calculator](https://chompthis.com/api/cost-calculator.php) | | [Terms & License](https://chompthis.com/api/terms.php) | [Database Search](https://chompthis.com/api/lookup.php) | | [Support](https://chompthis.com/api/ticket-new.php) | [Query Builder](https://chompthis.com/api/build.php) | | [Client Center](https://chompthis.com/api/manage.php) | | 
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// An object containing this item&#x27;s compatibility grades for each supported diet
    /// </summary>
    [DataContract]
        public partial class BrandedFoodObjectDietLabels :  IEquatable<BrandedFoodObjectDietLabels>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BrandedFoodObjectDietLabels" /> class.
        /// </summary>
        /// <param name="vegan">vegan.</param>
        /// <param name="vegetarian">vegetarian.</param>
        /// <param name="glutenFree">glutenFree.</param>
        public BrandedFoodObjectDietLabels(BrandedFoodObjectDietLabelsVegan vegan = default(BrandedFoodObjectDietLabelsVegan), BrandedFoodObjectDietLabelsVegetarian vegetarian = default(BrandedFoodObjectDietLabelsVegetarian), BrandedFoodObjectDietLabelsGlutenFree glutenFree = default(BrandedFoodObjectDietLabelsGlutenFree))
        {
            this.Vegan = vegan;
            this.Vegetarian = vegetarian;
            this.GlutenFree = glutenFree;
        }
        
        /// <summary>
        /// Gets or Sets Vegan
        /// </summary>
        [DataMember(Name="vegan", EmitDefaultValue=false)]
        public BrandedFoodObjectDietLabelsVegan Vegan { get; set; }

        /// <summary>
        /// Gets or Sets Vegetarian
        /// </summary>
        [DataMember(Name="vegetarian", EmitDefaultValue=false)]
        public BrandedFoodObjectDietLabelsVegetarian Vegetarian { get; set; }

        /// <summary>
        /// Gets or Sets GlutenFree
        /// </summary>
        [DataMember(Name="gluten_free", EmitDefaultValue=false)]
        public BrandedFoodObjectDietLabelsGlutenFree GlutenFree { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BrandedFoodObjectDietLabels {\n");
            sb.Append("  Vegan: ").Append(Vegan).Append("\n");
            sb.Append("  Vegetarian: ").Append(Vegetarian).Append("\n");
            sb.Append("  GlutenFree: ").Append(GlutenFree).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BrandedFoodObjectDietLabels);
        }

        /// <summary>
        /// Returns true if BrandedFoodObjectDietLabels instances are equal
        /// </summary>
        /// <param name="input">Instance of BrandedFoodObjectDietLabels to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BrandedFoodObjectDietLabels input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Vegan == input.Vegan ||
                    (this.Vegan != null &&
                    this.Vegan.Equals(input.Vegan))
                ) && 
                (
                    this.Vegetarian == input.Vegetarian ||
                    (this.Vegetarian != null &&
                    this.Vegetarian.Equals(input.Vegetarian))
                ) && 
                (
                    this.GlutenFree == input.GlutenFree ||
                    (this.GlutenFree != null &&
                    this.GlutenFree.Equals(input.GlutenFree))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Vegan != null)
                    hashCode = hashCode * 59 + this.Vegan.GetHashCode();
                if (this.Vegetarian != null)
                    hashCode = hashCode * 59 + this.Vegetarian.GetHashCode();
                if (this.GlutenFree != null)
                    hashCode = hashCode * 59 + this.GlutenFree.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
