/* 
 * Chomp Food Database API Documentation
 *
 * __Important:__   - An __[API key](https://chompthis.com/api/)__ is required for access to this API.   - Get yours at __[https://chompthis.com/api](https://chompthis.com/api/)__.  - -- --  __Getting Started:__   - __[Subscribe](https://chompthis.com/api/#pricing)__ to the API.   - Scroll down and click the \"__Authorize__\" button.   - Enter your API key into the \"__value__\" input, click the \"__Authorize__\" button, then click the \"__Close__\" button.   - Scroll down to the section titled \"__default__\" and click on the API endpoint you wish to use.   - Click the \"__Try it out__\" button.   - Enter the information the endpoint requires.   - Click the \"__Execute__\" button.  __Example:__    - __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/response-object.json)__ API response object.  - -- --  __How Do I Find My API Key?__   - Your API key was sent to the email address you used to create your subscription.   - You will also find your API key in the __[Client Center](https://chompthis.com/api/manage.php)__.   - _Read __[this article](https://desk.zoho.com/portal/chompthis/kb/articles/how-do-i-find-my-api-key)__ for more information._  ||| | - -- -- -- | - -- -- -- - | | [Knowledge Base](https://desk.zoho.com/portal/chompthis/kb/chomp) | [Pricing](https://chompthis.com/api/) | | [Attribution](https://chompthis.com/api/docs/attribution.php) | [Cost Calculator](https://chompthis.com/api/cost-calculator.php) | | [Terms & License](https://chompthis.com/api/terms.php) | [Database Search](https://chompthis.com/api/lookup.php) | | [Support](https://chompthis.com/api/ticket-new.php) | [Query Builder](https://chompthis.com/api/build.php) | | [Client Center](https://chompthis.com/api/manage.php) | | 
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BrandedFoodObjectPortions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BrandedFoodObjectPortionsTests
    {
        // TODO uncomment below to declare an instance variable for BrandedFoodObjectPortions
        //private BrandedFoodObjectPortions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BrandedFoodObjectPortions
            //instance = new BrandedFoodObjectPortions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BrandedFoodObjectPortions
        /// </summary>
        [Test]
        public void BrandedFoodObjectPortionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BrandedFoodObjectPortions
            //Assert.IsInstanceOfType<BrandedFoodObjectPortions> (instance, "variable 'instance' is a BrandedFoodObjectPortions");
        }


        /// <summary>
        /// Test the property 'MeasurementUnit'
        /// </summary>
        [Test]
        public void MeasurementUnitTest()
        {
            // TODO unit test for the property 'MeasurementUnit'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Modifier'
        /// </summary>
        [Test]
        public void ModifierTest()
        {
            // TODO unit test for the property 'Modifier'
        }
        /// <summary>
        /// Test the property 'GramWeight'
        /// </summary>
        [Test]
        public void GramWeightTest()
        {
            // TODO unit test for the property 'GramWeight'
        }
        /// <summary>
        /// Test the property 'DataPoints'
        /// </summary>
        [Test]
        public void DataPointsTest()
        {
            // TODO unit test for the property 'DataPoints'
        }
        /// <summary>
        /// Test the property 'Footnote'
        /// </summary>
        [Test]
        public void FootnoteTest()
        {
            // TODO unit test for the property 'Footnote'
        }

    }

}
